version: "3.8"

services:
    tests:
        build: 
            dockerfile: ./docker/test.dockerfile
            context: .
        image: tests_authentication
        container_name: tests_authentication
        env_file:
            - ./.env.test
        volumes:
            - ./reports/:/app/reports/:rw
        depends_on:
            - redis
            - postgres

    redis:
        image: redis:7.0-alpine
        container_name: redis_authentication
        networks:
            - network
        restart: always

    postgres:
        image: postgres:15.4-alpine
        container_name: postgres_authentication
        environment:
            - POSTGRES_USER=$DATABASE_USERNAME
            - POSTGRES_PASSWORD=$DATABASE_PASSWORD
        networks:
            - network
        restart: always

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
        container_name: elasticsearch_authentication
        environment:
            - discovery.type=single-node
            - ELASTIC_USERNAME=$ELASTIC_USERNAME
            - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
            - "xpack.security.enabled=false"
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - network

networks:
    network:
        driver: bridge
