{
 "title": "Authentication",
 "description": "Dashboard to show metrics about the microservice Authentication",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "development, sandbox, production"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests by Route",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expression": "floor($A * 60)", "type": "math" },
    { "expression": "floor($C * 60)", "type": "math" }
   ]
  },
  {
   "title": "Total Requests in 24h",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(nodejs_delay_http_requests_count{route!=\"/metrics\", env=\"$env\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests per Minute",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 12 },
   "targets": [
    { "expression": "floor($A * 60)", "type": "math" }
   ]
  }
 ]
}